<?php
/**
 * Created by PhpStorm.
 * User: simon
 * Date: 2016/9/24
 * Time: 6:45
 */

namespace Simon\Safe;


use Illuminate\Support\ServiceProvider;
use Simon\Safe\Contracts\SafeSubjectInterface;

class SafeServiceProvider extends ServiceProvider
{

    protected $defer = true;

    protected $configPath = __DIR__.'/../config/safe.php';

    public function boot()
    {
        $this->publishes([
            $this->configPath => config_path('safe.php'),
        ]);
    }


    public function register()
    {
        //合并 config
        $this->mergeConfigFrom($this->configPath, 'safe');

//        $this->app->singleton([Container::class=>'safe'],function(){
//            new Container($this->app['cache'],$this->app['request']);
//        });

        $this->app->singleton([SafeSubjectInterface::class=>'safe'],Container::class);
    }

    public function provides()
    {
        // TODO: Change the autogenerated stub
        return ['safe'];
    }
}